version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /home/app/node_modules
      - ./server:/home/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - my_network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /home/app/node_modules
      - ./worker:/home/app
    depends_on:
      - redis
      - server
    environment:
      - REDIS_HOST=redis
    networks:
      - my_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /home/app/node_modules
      - ./client:/home/app
    depends_on:
      - server
    environment:
      - VITE_EXPRESS_API_HOST=server
      - VITE_EXPRESS_API_PORT=3000
    networks:
      - my_network
    ports:
      - "5173:5173"

networks:
  my_network:
    driver: bridge
