version: "3"

services:
  redis:
    image: redis:latest

  nginx:
    restart: always
    depends_on:
      - client
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /home/app/node_modules
      - ./api:/home/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /home/app/node_modules
      - ./worker:/home/app
    depends_on:
      - redis
      - api
    environment:
      - REDIS_HOST=redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /home/app/node_modules
      - ./client:/home/app
    depends_on:
      - api
